CREATE TABLE IF NOT EXISTS noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_id INTEGER 
        REFERENCES noteful_folders(folder_id) ON DELETE CASCADE NOT NULL,
    note_name TEXT NOT NULL,
    date_modified TIMESTAMP DEFAULT now() NOT NULL,
    content TEXT NOT NULL
);